# Generated by Django 5.0.6 on 2024-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_telegramuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
