# Generated by Django 5.0.6 on 2024-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_telegramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
