# Generated by Django 5.0.6 on 2024-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_telegramuser_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
